### ISSUE TITLE
Better Graphics???

### ISSUE THREAD

**Issue by Light-Lens** [fegennari/3DWorld#10]
It's not bad but don't you think that it could render even more realistic graphics?

**Comment by fegennari** [comment]
Can you be more specific? Isn't this true for any game/game engine?

**Comment by Light-Lens** [comment]
> Can you be more specific? Isn't this true for any game/game engine?

i mean that this game engine has a really good potential, so if you managed to make it render even more realistic graphics, polish all it's a bit more and add more features to it, then this game engine can have even huge audience.

**Comment by fegennari** [comment]
I'm sure you're correct. If I had more time to work on this and better artistic skills I could definitely make improvements at a faster rate. It's limited by my time and my programmer art. And by my decision to only use open source components, free tools, and free/public assets. Maybe at some point I'll make a real game from this.
