### ISSUE TITLE
Hi. I press F1 when i in the scene, but can not change to the other world_model.

### ISSUE THREAD

**Issue by manman25** [fegennari/3DWorld#13]
its seems like the universe_only mode was set, then how i  can change my config?

**Comment by fegennari** [comment]
Did you ever get this working? I can't fix it without more feedback. Thanks.

**Comment by manman25** [comment]
> Did you ever get this working? I can't fix it without more feedback. Thanks.

Thank you! I have fixed this bug, and I am enjoying this project.

**Comment by fegennari** [comment]
Great, thanks. I'm closing this issue.
