### ISSUE TITLE
Character animation without rigging 

### ISSUE THREAD

**Issue by elkhalafy** [fegennari/3DWorld#16]
I found Idea for character animation without rigging or bones. This idea created by pixar studios called character articulation through profile curves or Curvenent system.
They have been released the paper about this idea, So please if you able to do this as standalone free software for Windows OS, It will be great

Look at the video and download the paper too

https://youtu.be/gUJ4RxMdVn8

Download the paper here :-

https://graphics.pixar.com/library/ProfileMover/paper.pdf

Please answer me for important.

Thank you

**Comment by fegennari** [comment]
Thanks for the links to the video and paper. This is impressive work by Pixar, and definitely something I expect and hope to see in their future movies. However, I feel that it's out of scope for 3DWorld. Implementing this requires creating a new interactive model editor, a new 3D model file format, and the runtime system for using this data. The first two are not tasks that I feel are on the planned path for 3DWorld. In addition, I don't think that I have the artistic skills to create high quality animated models. It's not even clear how I would take advantage of the benefits of this system for my limited use of people and animal models, which currently fit my needs. I prefer to wait to see if this technique catches on, and then maybe I can download 3D models that have already been animated in this way.

**Comment by elkhalafy** [comment]
Thank you for your answer me

You are welcome.

In fact they already rewrite their software called Presto by their research and they already first test with turning red movie Panda character, and he first full movie is lighteryear. The full movie created by this technique. 

Yes, I need from you to create new free 3d software for character animation based on the paper of pixar, it's interactive way and Curvenent system is based on splines. Animation based on splines or curves. Without rigging nor Weights painting nor binding. It's interactive way, 

No, you don't need new files formats. It's same fbx, 3ds, GLTF, etc..  if you created it, you will support these formats without any problems. No interactive formats not special formats for this idea. But the issue is you can't export files with this system of animation inside blender or Maya or any software that still support bones and weights painting and skinning system. At least you should write plugin or add-on inside each software in Maya or blender or any software to help importing this character that you animated without rigging inside blender fot example and works on timeline and software perfectly. you got it.

As I see you don't need to create it, it's very hard or what? 
If you able already I hope starting to create it, it's biggest dream ever. The paper explains everything.

**Comment by fegennari** [comment]
This is a different type of animation that's per-mesh polygon rather than per-bone/vertex. I don't believe existing 3D model formats support this. This requires a new toolchain. It's not something you can ask someone to implement as a free product. For all I know, Pixar may have patented the technology to prevent someone from making a product that does this.

Anyway, I'm pretty busy with procedural generation and other projects. I don't have time to attempt this. It's a very new tech though. Maybe if you wait someone will create a tool or a Blender/Maya/etc. plugin for this.

**Comment by elkhalafy** [comment]
Pixar may have patented the technology to prevent someone from making a product that does this.   if so, why they released the paper  !!?
Paper covers the main concept with how it works too ?

If you would not like to do this, never mind

Thank you anyway

**Comment by fegennari** [comment]
It happens all the time. They publish the paper to show off what they've done and to get their customers and business partners to work with them on the tech. They want others in the industry using their inventions. But they may not want someone writing a free tool that allows others to use that idea without involving them.

The company I work for does this same thing: patent an invention and then publish a conference paper on it. It's common in my industry. This is why I'm aware of the risks.

I'm not saying that Pixar patented Curvenet or has this mindset. I'm only saying that the first step in implementing it would be to check on this to make sure there's no patent infringement. But in any case, I'm not interested in this task right now.

**Comment by fegennari** [comment]
I looked and Pixar has 507 patent filings, 390 of which have been granted. Curvenets doesn't seem to be patented, but the application may have been submitted and not yet granted.
