### ISSUE TITLE
Support AVIF

### ISSUE THREAD

**Issue by GrimPixel** [fegennari/3DWorld#21]
In some sources, it is more advanced than WebP. So I think AVIF format can be supported.

**Comment by fegennari** [comment]
AVIF is an image format mostly used by web browsers and not something I've ever seen used with 3D models. 3DWorld isn't intended to be used through the web, so it's not clear that AVIF format support is need. Do you have a 3D model that includes images of this format? If not, then why do you feel that AVIF needs to be supported?

In addition, the stb_image library used in 3DWorld doesn't support AVIF format. If this is added in the future, I will update the stb_image header and it should pick up AVIF support automatically.

**Comment by GrimPixel** [comment]
It is not only used for the web. It is supported by image viewers like [nomacs](https://github.com/nomacs/nomacs/issues/292) and [qView](https://github.com/jurplel/qView/issues/274), as well as [Godot](https://github.com/gd-avif/gd-avif) as an extension. It is not supported by Blender yet.
Available libraries are [libavif](https://github.com/AOMediaCodec/libavif) and [libheif](https://github.com/strukturag/libheif).

**Comment by fegennari** [comment]
I've never come across any AVIF files, so I don't see the need to add support for this format to 3DWorld. Maybe some time in the future.

**Comment by fegennari** [comment]
No planned at this time. I will reopen if this comes up in an actual model or image I need to load.
