### ISSUE TITLE
The latest version of openal-soft no longer has the file alut.h

### ISSUE THREAD

**Issue by sui0312feng** [fegennari/3DWorld#25]
The latest version of openal-soft no longer has the file alut.h, can you change to the latest version of openal-soft to change your program?

**Comment by fegennari** [comment]
I don't believe OpenAL ever contained alut.h. This file comes from freealut, which is a different library. I got mine from here:
https://github.com/vancegroup/freealut

In fact alut.h is already included in the 3DWorld repo:
https://github.com/fegennari/3DWorld/blob/master/dependencies/freealut/include/AL/alut.h

This should already be included in the Visual Studio project. And for linux I always just installed libopenal (see README.linux). What platform/compiler are you building on? And what specific errors do you get?
