### ISSUE TITLE
Windows test run

### ISSUE THREAD

**Issue by Juris3D** [fegennari/3DWorld#3]
I have very egoistic lazy proposition :) How about upload time to time some Windows compiled executable? ;-) I know, options are now in manual editing .ini, so it is not that straightforward maybe.... but what Author says about such idea? :) Thanks.

**Comment by fegennari** [comment]
Do you mean adding my Windows compiled binary to the 3DWorld git repo? I can try, but it likely won't run on all versions of Windows. You'll need all of the various Microsoft runtime libraries for the version of Visual Studio I'm using, and your installed DLLs for various things must match mine (unless I add the DLLs as well).

It won't work with all of my config files when I add new options. I can't update the binary every time I add new options. That will make the git repo grow too quickly. Each exe is 5.1MB and git may not be able to store the changes as deltas.

I'm not sure what this has to do with .ini files.

**Comment by Lecrapouille** [comment]
Do not include your exec files inside your sources. This will blow up time the time for git cloning your code. Github has services for this. https://help.github.com/en/articles/distributing-large-binaries

**Comment by Juris3D** [comment]
sorry i meant config files, not .ini
And - no, i did not mean to include exes on github. I meant some Google Drive, DropBox, SomethingCloud executable, to easily get taste of project :)

**Comment by fegennari** [comment]
I created a V1.0 release with 32-bit Windows debug + release EXE files. You would still need all of the assets from the git repo as well. Just drop one of these files into the root directory and see if it works. Maybe it should go into a sub directory named "bin", or in the "Debug" and "Release" directories used by Visual Studio. There are probably a lot of required DLLs as well, but maybe users can download these from somewhere.

Juris, can you see if these EXE files work on your Windows PC?

I could probably do the same for Linux, but I think the binaries are less likely to work on other machines. They would likely only work on machines with the same/similar linux kernels (or glibc version) and OpenGL version.

**Comment by Juris3D** [comment]
Hello, thats great news about EXE! :) Well today in Latvia we have super-fest of the year (Ligo in Latvia, look it up), but I sure will test it at some moment and come back with experiences! Thank You!

**Comment by Juris3D** [comment]
Good initial news: Unpacked "release source", but .exe-s there in root, run 3Dworld.exe - familiar building scene starts right away with no visible problems :)
Now I guess I will have to go thru all configs in "defaults.txt" to get cities and stuff? :) I will try now. 
But, point is, those release downloads started fine. Thank You.

**Comment by fegennari** [comment]
If the release build works on one scene it should work on them all, at least as well as a build you create yourself. I'm going to mark this issue closed now. I'll try to remember to create new builds at regular intervals.

**Comment by Juris3D** [comment]
Thank you! Your quick recommendations for testing cities? is there infinite cities now? Is there "flying me" to test in maps? :) Need to read docs, i know, hehe

**Comment by Juris3D** [comment]
Oh, probably need to state visible somewhere at release - "Press F1 after starting particular config"

**Comment by Juris3D** [comment]
City is working, with cars and yellow balls pedestrians :)
I could list ones that does not start:
Config Universe, River, Berkeley, Puget, Puget Sound, Grand Canyon, Grand Canyon Sound, Hetch, Config Soda, San Miquel, White Plane.

**Comment by fegennari** [comment]
The 'F1' key switches between normal/ground/gameplay mode, universe mode, and tiled terrain mode. There are config file options to set which mode to start in and which modes are disabled. The ones that should start in tiled terrain mode shouldn't require using 'F1'. Which one do you need to use 'F1' on? I can change the defaults.

The pedestrians are yellow balls if the models haven't been loaded. I have about 800MB of car and pedestrian models. Maybe I can put them up somewhere you can download from? But some of the licenses may not allow them to be redistributed.
