### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fegennari/3DWorld#7]
Would you like to add more error handling for return values from functions like the following?
- [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [texture_t::write_to_bmp](https://github.com/fegennari/3DWorld/blob/38b86c47c10eea4ce1cbec2de6a0b94f66a0d797/src/image_io.cpp#L334)
- [fseek](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [ImageGetRow](https://github.com/fegennari/3DWorld/blob/ed4b07fc532e724376ebb8f13af178ae901a1442/src/Loadlum.cpp#L108)

**Comment by fegennari** [comment]
Thanks. How did you find these? Some static code analysis tool? There are 68 fclose() calls and 8 fseek() calls, none of which have their return values checked. I didn't realize it was possible for these to fail (and it's often not checked in other projects). It's too much work to update all 76 cases to print the proper error message with filename, etc. What I did was wrap these functions in checked versions that print an error and exit with code 1. If I ever see one fail I'll go back and add a better error message printout.

**Comment by elfring** [comment]
>How did you find these?

I performed a simple source code search.


>I didn't realize it was possible for these to fail …

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?


>What I did was wrap these functions in checked versions …

Thanks for [your change acceptance](https://github.com/fegennari/3DWorld/commit/d891d7e02fb6600e71482b06827cff3021881c00 "Checking more return values").

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by fegennari** [comment]
I'm not familiar with aspect-oriented software development. Based on a brief look at your linked sites, it looks like porting 3DWorld's 124K lines of code to this format requires significant effort. While it may make sense to start a new project using aspect-oriented principles, it doesn't make sense for me to switch 3DWorld at this time. I prefer to focus on the graphics, physics, AI, and procedural generation areas of my project. I'm less interested in C++ design patterns and language features. However, thank you for the suggestion.

For static source code analysis, I'm already using the built-in analysis provided by Microsoft Visual Studio 2019. This will hopefully find the most important code issues. I can try other analysis tools if I have time later. We have some good linux code analysis tools available at my work, but they're not free for use in my project at home.

**Comment by elfring** [comment]
>I prefer to focus on …

Would you care for [a nicer handling of cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Description for cross-cutting concerns")?


>I can try other analysis tools …

How do you think about to try alternatives out like the following?
* [Cppcheck](http://cppcheck.sourceforge.net/ "C/C++ code analysis")
* [Semantic patch language (Coccinelle)](http://coccinelle.lip6.fr/ "Source code transformation by Coccinelle")

**Comment by fegennari** [comment]
I'll look into cppcheck, but I'm not too interested in the others. We have cppcheck installed and work and I ran it on our code base, but it only found false positives and violations in unused files. Thanks.

**Comment by elfring** [comment]
:crystal_ball: I am curious if your software development attention will grow around the discussed implementation details.
