### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [fegennari/3DWorld#9]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/113686855-4e9f8680-96fa-11eb-9e91-86f23826a993.png)

thank you  
best regards to you  
William

**Comment by fegennari** [comment]
This is a simple error when calling max() on a 32-bit vs. 64-bit unsigned number. I normally build on Windows/Visual Studio in 32-bit, and I don't see those errors. I assume you're building with gcc with a 64-bit build. I only test gcc/linux builds every week or so, and this error was from a recent change. It should be fixed now. Thanks for pointing this out to me.
